CREATE TABLE `defaultdb`.`Accounts` (
    `Id` INT PRIMARY KEY AUTO_INCREMENT,
    `UserId` INT NOT NULL,
    `Title` VARCHAR(255) NOT NULL DEFAULT '',
    `Type` VARCHAR(255) NOT NULL,
    `GroupId` INT NOT NULL DEFAULT -1,
    `Website_URL` VARCHAR(255),
    `Username` VARCHAR(255) DEFAULT '',
    `Email` VARCHAR(255) DEFAULT '',
    `Phone` VARCHAR(50) DEFAULT '',
    `Password` VARCHAR(255) DEFAULT '',
    `TwoFactor` VARCHAR(255) DEFAULT '',
    `Notes` VARCHAR(4000) DEFAULT '',
    `IsFavorite` BOOLEAN NOT NULL DEFAULT FALSE,
    `CreatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `UpdatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `defaultdb`.`Notes` (
    `Id` INT PRIMARY KEY AUTO_INCREMENT,
    `UserId` INT NOT NULL,
    `Title` VARCHAR(255) NOT NULL,
    `Group` VARCHAR(255) NOT NULL DEFAULT 'default',
    `Notes` TEXT,
    `IsFavorite` BOOLEAN NOT NULL DEFAULT FALSE,
    `CreatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `UpdatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `defaultdb`.`Groups` (
    `Id` INT AUTO_INCREMENT PRIMARY KEY,
    `UserId` INT NOT NULL,
    `Title` VARCHAR(255) NOT NULL,
    `Type` VARCHAR(50) NOT NULL,
    `LucideIcon` VARCHAR(255) DEFAULT '<Archive className="h-4 w-4 text-icon-primary" />',
    `CanDelete` BOOLEAN NOT NULL,
    `IsFavorite` BOOLEAN DEFAULT FALSE,
    `CreatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `UpdatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);



