CREATE TABLE `defaultdb`.`Accounts` (
    `Id` INT PRIMARY KEY AUTO_INCREMENT,
    `UserId` INT NOT NULL,
    `Title` VARCHAR(255) NOT NULL,
    `GroupId` INT NOT NULL DEFAULT 0,
    `Website_URL` VARCHAR(255) DEFAULT '',
    `Username` VARCHAR(255) DEFAULT '',
    `Email` VARCHAR(255) DEFAULT '',
    `Phone` VARCHAR(50) DEFAULT '',
    `Password` VARCHAR(255) DEFAULT '',
    `TwoFactor` VARCHAR(255) DEFAULT '',
    `Notes` VARCHAR(4000) DEFAULT '',
    `IsFavorite` BOOLEAN NOT NULL DEFAULT FALSE,
    `CreatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `UpdatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `defaultdb`.`Notes` (
    `Id` INT PRIMARY KEY AUTO_INCREMENT,
    `UserId` INT NOT NULL,
    `Title` VARCHAR(255) NOT NULL,
    `Group` VARCHAR(255) NOT NULL DEFAULT 'default',
    `Notes` TEXT,
    `IsFavorite` BOOLEAN NOT NULL DEFAULT FALSE,
    `CreatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `UpdatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `defaultdb`.`Groups` (
    `Id` INT AUTO_INCREMENT,
    `UserId` INT PRIMARY KEY NOT NULL,
    `Title` VARCHAR(255) NOT NULL,
    `Description` VARCHAR(1000) DEFAULT '',
    `CreatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `UpdatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);



